---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: completed-pods-cron-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/status
    verbs:
      - get
      - list
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: completed-pods-cron-binding
roleRef:
  name: completed-pods-cron-role
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
subjects:
  - name: pod-cleanup-sa
    namespace: sre-namespace
    kind: ServiceAccount
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: delete-completed-pods
  namespace: sre-namespace
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  schedule: "0 0 * * 6"
  successfulJobsHistoryLimit: 3
  suspend: false
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: pod-cleanup-sa
          restartPolicy: Never
          containers:
            - name: delete-completed-pods
              image: UPDATE WITH OC IMAGE HERE
              imagePullPolicy: IfNotPresent
              resources: {}
              command:
                - /bin/bash
                - -c
                - |
                  PODS_TO_DELETE=$(oc get pods -A -o custom-columns=NS:.metadata.namespace,NAME:.metadata.name,PHASE:.status.phase --no-headers | \
                    grep '^openshift-' | \
                    grep 'Succeeded' | \
                    awk '{print $1, $2}')
                  
                  if [ -z "$PODS_TO_DELETE" ]; then
                    echo "No matching Completed pods found in openshift-* namespaces. Exiting."
                    exit 0
                  fi
                  
                  DELETION_COUNT=0
                  
                  while read -r NAMESPACE NAME; do
                    if [[ -n "$NAMESPACE" && -n "$NAME" ]]; then
                      echo "Deleting pod: $NAMESPACE/$NAME"
                      if oc delete pod "$NAME" -n "$NAMESPACE" --grace-period=0 --force --ignore-not-found &> /dev/null; then
                        ((DELETION_COUNT++))
                      fi
                    fi
                  done <<< "$PODS_TO_DELETE"
                  
                  echo "--- $(date '+%Y-%m-%d %H:%M:%S') - Cleanup Finished: Deleted $DELETION_COUNT Pod(s) ---"
                  exit 0
delete completed.txt
Displaying delete completed.txt.